// Generated by https://quicktype.io

import type { ApiBaseResponse } from '@/modules/common/types/common-interface';
import type { User } from '@/modules/auth/interfaces/user.interface';

export interface AuthResponse extends ApiBaseResponse {
  data: User;
}
